print('Enter amount of lemon juice (in cups):')
Lcups = float(input())
print('Enter amount of water (in cups):')
Wcups = float(input())
print('Enter amount of agave nectar (in cups):')
Acups = float(input())
print('How many servings does this make?\n')
Servings = float(input())
print('Lemonade ingredients - yields', '{:.2f}'.format(Servings), 'servings')
print('{:.2f}'.format(Lcups), 'cup(s) lemon juice')
print('{:.2f}'.format(Wcups), 'cup(s) water')
print('{:.2f}'.format(Acups), 'cup(s) agave nectar\n')
print('How many servings would you like to make?\n')
ServM = float(input())
Multi = (ServM / 6.0)

print('Lemonade ingredients - yields', '{:.2f}'.format(ServM), 'servings')
print('{:.2f}'.format((Lcups * Multi)), 'cup(s) lemon juice')
print('{:.2f}'.format(Wcups * Multi), 'cup(s) water')
print('{:.2f}'.format(Acups * Multi), 'cup(s) agave nectar\n')
print('Lemonade ingredients - yields', '{:.2f}'.format(ServM), 'servings')
print('{:.2f}'.format((Lcups * Multi)/16), 'gallon(s) lemon juice')
print('{:.2f}'.format((Wcups * Multi)/16), 'gallon(s) water')
print('{:.2f}'.format((Acups * Multi)/16), 'gallon(s) agave nectar')
